spring:
  application:
    name: ensino
# h2
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:ensino;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=MySQL;
#    username: admin
#    password: 

# sql server
#  datasource:
#    url: jdbc:sqlserver://ensino.database.windows.net:1433;database=ensino;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: thiago
#    password: Tms030586@

  datasource:
    url: jdbc:sqlserver://sv-fiap-database.database.windows.net:1433;database=db-fiap-cursos;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: fiap-database@sv-fiap-database
    password: rm@361303

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  messages:
    encoding: ISO-8859-1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    context-path: /ensino
  port: 8085